### ISSUE TITLE
Merge char ranges

### ISSUE THREAD

**Issue by kpp** [suhr/sana#54]
In the generated code there are a lot of ranges of chars stepping each other:

```
...
                | '\u{16b50}'..='\u{16b59}'
                | '\u{16b5a}'..='\u{1d7cd}'
                | '\u{1d7ce}'..='\u{1d7ff}'
...
```

Where 16b5a is followed 16b59 and so on.

We should merge them.

**Comment by suhr** [comment]
Fixed by #57.
